.TH "C:/Users/Stefan/Documents/GitHub/CSM6120_Assignment2/New folder/html/d4/d45 Directory Reference" 3 "Sun Nov 30 2014" "Version 1.0" "CSM6120 Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Stefan/Documents/GitHub/CSM6120_Assignment2/New folder/html/d4/d45 Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclasscsm6120__assignment2_1_1_file_manager_test\&.js\fP"
.br
.in -1c
