.TH "C:/Users/Stefan/Documents/GitHub/CSM6120_Assignment2/New folder/html/d5 Directory Reference" 3 "Sun Nov 30 2014" "Version 1.0" "CSM6120 Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Stefan/Documents/GitHub/CSM6120_Assignment2/New folder/html/d5 Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBd2c\fP"
.br
.in -1c
