.TH "C:/Users/Stefan/Documents/GitHub/CSM6120_Assignment2/New folder/html/df/da1 Directory Reference" 3 "Sun Nov 30 2014" "Version 1.0" "CSM6120 Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Stefan/Documents/GitHub/CSM6120_Assignment2/New folder/html/df/da1 Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclasssearch___algortihms_1_1_a_star\&.js\fP"
.br
.in -1c
