.TH "csm6120_assignment2.StateTest" 3 "Sun Nov 30 2014" "Version 1.0" "CSM6120 Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csm6120_assignment2.StateTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtearDown\fP ()"
.br
.ti -1c
.RI "void \fBtestAddState\fP ()"
.br
.ti -1c
.RI "void \fBtestPrintArray\fP ()"
.br
.ti -1c
.RI "void \fBtestReturn_index\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetUpClass\fP ()"
.br
.ti -1c
.RI "static void \fBtearDownClass\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Stefan 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void csm6120_assignment2\&.StateTest\&.testAddState ()"
Test of addState method, of class \fBState\fP\&. 
.SS "void csm6120_assignment2\&.StateTest\&.testPrintArray ()"
Test of printArray method, of class \fBState\fP\&. 
.SS "void csm6120_assignment2\&.StateTest\&.testReturn_index ()"
Test of return_index method, of class \fBState\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CSM6120 Assignment from the source code\&.
