.TH "csm6120_assignment2.FileManager" 3 "Sun Nov 30 2014" "Version 1.0" "CSM6120 Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csm6120_assignment2.FileManager \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileManager\fP ()"
.br
.ti -1c
.RI "void \fBreader\fP (\fBState\fP s, File path)"
.br
.ti -1c
.RI "void \fBfindInteger\fP (String s, \fBState\fP state)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class holds methods to manipulate the input files\&.
.PP
\fBAuthor:\fP
.RS 4
stefan 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "csm6120_assignment2\&.FileManager\&.FileManager ()"
Constructor of the \fBFileManager\fP class 
.SH "Member Function Documentation"
.PP 
.SS "void csm6120_assignment2\&.FileManager\&.findInteger (Strings, \fBState\fPstate)"
Changes the input line from being Strings to single Integers\&. 
.PP
\fBParameters:\fP
.RS 4
\fIs\fP The String to analyse and change 
.br
\fIstate\fP The \fBState\fP object to save too 
.RE
.PP

.SS "void csm6120_assignment2\&.FileManager\&.reader (\fBState\fPs, Filepath)"
Read a given file path and calls the \fBfindInteger()\fP method\&. This is used to read the input files and read them line for line\&.
.PP
\fBParameters:\fP
.RS 4
\fIs\fP The \fBState\fP object to save too 
.br
\fIpath\fP The path of the input file 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CSM6120 Assignment from the source code\&.
