.TH "csm6120_assignment2.Main" 3 "Sun Nov 30 2014" "Version 1.0" "CSM6120 Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csm6120_assignment2.Main \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is the entrance to the program\&.
.PP
\fBAuthor:\fP
.RS 4
stefan 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void csm6120_assignment2\&.Main\&.main (String[]args)\fC [static]\fP"
\fBMain\fP method of the program\&. This method can be called from the command line with a set of arguments\&.
.PP
javac main theStartFile theGoalFile theAlgorithmToUse
.PP
where theStartFile is a text file holding the start \fBState\fP, theGoalFile holds the goal \fBState\fP of the puzzle\&. TheAlgorithmToUse specifies which algorithm, possibilities are:
.PP
bfs - Breadth-First search dfs - Depth-First search gbfs - Greedy Best-First search astar - A* search
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP the command line arguments 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CSM6120 Assignment from the source code\&.
