.TH "md__c_1__users__stefan__documents__git_hub__c_s_m6120__assignment2__r_e_a_d_m_e" 3 "Sun Nov 30 2014" "Version 1.0" "CSM6120 Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1__users__stefan__documents__git_hub__c_s_m6120__assignment2__r_e_a_d_m_e \- CSM6120 Assignment 2: Solving 8-puzzles with uninformed and informed search 
Project requires command line arguments to work: java Main <path to='' start='' file>=''> 
