.TH "search_Algortihms.BFS" 3 "Sun Nov 30 2014" "Version 1.0" "CSM6120 Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
search_Algortihms.BFS \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBFS\fP ()"
.br
.ti -1c
.RI "void \fBbfs\fP (\fBState\fP start, \fBState\fP goal)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class file for the Breadth first search algorithm
.PP
\fBAuthor:\fP
.RS 4
stefan 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "search_Algortihms\&.BFS\&.BFS ()"
Constructor of the \fBBFS\fP object 
.SH "Member Function Documentation"
.PP 
.SS "void search_Algortihms\&.BFS\&.bfs (\fBState\fPstart, \fBState\fPgoal)"
Breath-First search method
.PP
\fBParameters:\fP
.RS 4
\fIstart\fP The start State of the graph 
.br
\fIgoal\fP The goal State of the graph 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CSM6120 Assignment from the source code\&.
