.TH "search_Algortihms.StateComparator" 3 "Sun Nov 30 2014" "Version 1.0" "CSM6120 Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
search_Algortihms.StateComparator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Comparator< TreeNode >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBcompare\fP (\fBTreeNode\fP o1, \fBTreeNode\fP o2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is used to compare to states together\&. Implements the Comparator interface
.PP
\fBAuthor:\fP
.RS 4
Stefan 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "int search_Algortihms\&.StateComparator\&.compare (\fBTreeNode\fPo1, \fBTreeNode\fPo2)"
Method to compare 2 TreeNode objects for order\&. Compares 2 objects state string representation and orders them based on their natural ordering i\&.e\&. 0 1 2 3 4 5 6 7 8
.PP
\fBParameters:\fP
.RS 4
\fIo1\fP TreeNode object 1 to compare 
.br
\fIo2\fP TreeNode object 2 to compare 
.RE
.PP
\fBReturns:\fP
.RS 4
a negative integer, zero, or a positive integer as the first argument is less than, equal to, or greater than the second 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CSM6120 Assignment from the source code\&.
